name = "fastapi"
compatibility_date = "2024-05-03"

[vars]
UPSTASH_REDIS_REST_TOKEN = 'Acn4AAIncDE3ZWIwNTRjYTEyNzY0NzE4YjY2MGE1NmUzZDE4M2UzMHAxNTE3MDQ'
UPSTASH_REDIS_REST_URL = 'https://frank-grubworm-51704.upstash.io'